services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Dados_RFB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cnpj_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_container
    volumes:
      - ./code:/usr/src/app
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Dados_RFB
    networks:
      - cnpj_network

networks:
  cnpj_network:
